package jp.co.loft.backoffice.api.common.message;
/**
 * Message Id(MessageKeysGenクラスの実行による自動生成クラス)
 */
public class MessageKeys {
    /** w.BOA-V101=HttpRequest method not supported. */
    public static final String W_BOA_V101 = "w.BOA-V101";
    /** w.BOA-V102=Request handling method not supported. */
    public static final String W_BOA_V102 = "w.BOA-V102";
    /** w.BOA-V103=Specified Http media type representation format not supported. */
    public static final String W_BOA_V103 = "w.BOA-V103";
    /** w.BOA-V104=Specified Http media type in the request body not supported. */
    public static final String W_BOA_V104 = "w.BOA-V104";
    /** w.BOA-V105=Validation error occurred on item in the request body. */
    public static final String W_BOA_V105 = "w.BOA-V105";
    /** w.BOA-V106=Validation error occurred on item in the request parameters. */
    public static final String W_BOA_V106 = "w.BOA-V106";
    /** w.BOA-V107=Validation error occurred on item in the request body. */
    public static final String W_BOA_V107 = "w.BOA-V107";
    /** w.BOA-V108=Servlet request binding. */
    public static final String W_BOA_V108 = "w.BOA-V108";
    /** w.BOA-V109=HttpMessage not readable. */
    public static final String W_BOA_V109 = "w.BOA-V109";
    /** w.BOA-V110=HttpMessage not writable. */
    public static final String W_BOA_V110 = "w.BOA-V110";
    /** w.BOA-V111=Missing servlet request part. */
    public static final String W_BOA_V111 = "w.BOA-V111";
    /** w.BOA-V112=Request JSON body format error occurred. */
    public static final String W_BOA_V112 = "w.BOA-V112";
    /** w.BOA-V113=Unknown field exists in JSON. */
    public static final String W_BOA_V113 = "w.BOA-V113";
    /** w.BOA-V114=Type mismatch error occurred in JSON field. */
    public static final String W_BOA_V114 = "w.BOA-V114";
    /** w.BOA-V115=Conversion not supported. */
    public static final String W_BOA_V115 = "w.BOA-V115";
    /** w.BOA-V116=Type mismatch error occurred in request parameter or header or path variable. */
    public static final String W_BOA_V116 = "w.BOA-V116";
    /** w.BOA-D101=Resource not found. */
    public static final String W_BOA_D101 = "w.BOA-D101";
    /** w.BOA-D102=Business error occurred. */
    public static final String W_BOA_D102 = "w.BOA-D102";
    /** w.BOA-D103=Conflict with other processing occurred. */
    public static final String W_BOA_D103 = "w.BOA-D103";
    /** w.BOA-D104=Conflict with other processing occurred. */
    public static final String W_BOA_D104 = "w.BOA-D104";
    /** e.BOA-5001=System error occurred. */
    public static final String E_BOA_5001 = "e.BOA-5001";
    /** e.BOA-5002=System error occurred. */
    public static final String E_BOA_5002 = "e.BOA-5002";
    /** e.BOA-5003=System error occurred. */
    public static final String E_BOA_5003 = "e.BOA-5003";
    /** typeMismatch={0} is invalid. */
    public static final String TYPEMISMATCH = "typeMismatch";
    /** typeMismatch.int={0} must be an integer. */
    public static final String TYPEMISMATCH_INT = "typeMismatch.int";
    /** typeMismatch.double={0} must be a double. */
    public static final String TYPEMISMATCH_DOUBLE = "typeMismatch.double";
    /** typeMismatch.float={0} must be a float. */
    public static final String TYPEMISMATCH_FLOAT = "typeMismatch.float";
    /** typeMismatch.long={0} must be a long. */
    public static final String TYPEMISMATCH_LONG = "typeMismatch.long";
    /** typeMismatch.short={0} must be a short. */
    public static final String TYPEMISMATCH_SHORT = "typeMismatch.short";
    /** typeMismatch.boolean={0} must be a boolean. */
    public static final String TYPEMISMATCH_BOOLEAN = "typeMismatch.boolean";
    /** typeMismatch.java.lang.Integer={0} must be an integer. */
    public static final String TYPEMISMATCH_JAVA_LANG_INTEGER = "typeMismatch.java.lang.Integer";
    /** typeMismatch.java.lang.Double={0} must be a double. */
    public static final String TYPEMISMATCH_JAVA_LANG_DOUBLE = "typeMismatch.java.lang.Double";
    /** typeMismatch.java.lang.Float={0} must be a float. */
    public static final String TYPEMISMATCH_JAVA_LANG_FLOAT = "typeMismatch.java.lang.Float";
    /** typeMismatch.java.lang.Long={0} must be a long. */
    public static final String TYPEMISMATCH_JAVA_LANG_LONG = "typeMismatch.java.lang.Long";
    /** typeMismatch.java.lang.Short={0} must be a short. */
    public static final String TYPEMISMATCH_JAVA_LANG_SHORT = "typeMismatch.java.lang.Short";
    /** typeMismatch.java.lang.Boolean={0} is not a boolean. */
    public static final String TYPEMISMATCH_JAVA_LANG_BOOLEAN = "typeMismatch.java.lang.Boolean";
    /** typeMismatch.java.util.Date={0} is not a date. */
    public static final String TYPEMISMATCH_JAVA_UTIL_DATE = "typeMismatch.java.util.Date";
    /** typeMismatch.java.lang.Enum={0} is not a valid value. */
    public static final String TYPEMISMATCH_JAVA_LANG_ENUM = "typeMismatch.java.lang.Enum";
    /** shopCd=Shop code */
    public static final String SHOPCD = "shopCd";
    /** terminalNum=Terminal number */
    public static final String TERMINALNUM = "terminalNum";
    /** userId=User id */
    public static final String USERID = "userId";
    /** odrNum=Order number */
    public static final String ODRNUM = "odrNum";
    /** odrStatus=Order status */
    public static final String ODRSTATUS = "odrStatus";
    /** prdctCd=Product code */
    public static final String PRDCTCD = "prdctCd";
    /** inspectionQntty=Inspection quantity */
    public static final String INSPECTIONQNTTY = "inspectionQntty";
    /** inspectionNum=Inspection number */
    public static final String INSPECTIONNUM = "inspectionNum";
    /** shipmentKbn=Shipment code */
    public static final String SHIPMENTKBN = "shipmentKbn";
}
